###
POST https://localhost:5001/petshop/pessoa/create
Content-Type: application/json

{
"Nome" : "José",
"CPF" : 59267069272,
"Funcao" : "Limpador",
"Telefone" : 41992223985
}

###
POST https://localhost:5001/petshop/pet/create
Content-Type: application/json

{
"Nome" : "iiio",
"IdPet" : 1,
"Dono" : "Jose",
"TipoAnimal" : "Lagarto"
}