
### Cadastrar Pet
POST https://localhost:5001/petshop/pet/create
Content-Type: application/json

{
"Nome" : "Tigre",
"Dono" : "Jose",
"TipoAnimal" : "Gato"
}


### Listar Pets
GET https://localhost:5001/petshop/pet/list

### Buscar Pet pelo ID

GET https://localhost:5001/petshop/pet/getbyid/3


### Alterar Pet

PUT https://localhost:5001/petshop/pet/update
Content-Type: application/json

{
"PetId" : 1,
"Nome" : "Alterado",
"Dono" : "Car",
"TipoAnimal" : "Dog"
}


### Deletar Pet
 
DELETE https://localhost:5001/petshop/pet/delete/Tigre