###
POST https://localhost:5001/petshop/pessoa/create
Content-Type: application/json

{
"Nome" : "José",
"Funcao" : "Limpador"
}

###
POST https://localhost:5001/petshop/pet/create
Content-Type: application/json

{
"Nome" : "iiio",
"Dono" : "Jose",
"TipoAnimal" : "Gato"
}

###

GET https://localhost:5001/petshop/pet/list
